### ISSUE TITLE
Issue with astrospice.generate_coords()

### ISSUE THREAD

**Issue by MohamedNedal** [astrospice/astrospice#22]
Hello, I have 

```
astropy: 4.3.1
sunpy: 3.1.6
astrospice: 0.1.0
```

and I got the following error: 

```
start_obstime = Time('2019-04-01T00:00:00.000')
end_obstime = Time('2019-04-01T23:51:51.000')
```

```
dt = TimeDelta(1 * u.day)
times = Time(np.arange(start_obstime, end_obstime, dt))
coords = astrospice.generate_coords('SOLAR PROBE PLUS', times) 
```

---------------------------------------------------------------------------
SpiceSPKINSUFFDATA                        Traceback (most recent call last)
<ipython-input-7-51cb75d8e94b> in <module>
      4 dt = TimeDelta(1 * u.day)
      5 times = Time(np.arange(start_obstime, end_obstime, dt))
----> 6 coords = astrospice.generate_coords('SOLAR PROBE PLUS', times)

/opt/anaconda3/lib/python3.7/site-packages/astrospice/coords.py in generate_coords(body, times)
     29     pos_vel, lightTimes = spiceypy.spkezr(
     30         body.name, times_et, frame, abcorr,
---> 31         'SOLAR SYSTEM BARYCENTER')
     32 
     33     positions = np.array(pos_vel)[:, :3] * u.km

/opt/anaconda3/lib/python3.7/site-packages/spiceypy/spiceypy.py in with_errcheck(*args, **kwargs)
    121     def with_errcheck(*args, **kwargs):
    122         try:
--> 123             res = f(*args, **kwargs)
    124             check_for_spice_error(f)
    125             return res

/opt/anaconda3/lib/python3.7/site-packages/spiceypy/spiceypy.py in spkezr(targ, et, ref, abcorr, obs)
  12002                 targ, ctypes.c_double(t), ref, abcorr, obs, starg, ctypes.byref(lt)
  12003             )
> 12004             check_for_spice_error(None)
  12005             states.append(stypes.c_vector_to_python(starg))
  12006             times.append(lt.value)

/opt/anaconda3/lib/python3.7/site-packages/spiceypy/spiceypy.py in check_for_spice_error(f)
    106         reset()
    107         raise stypes.dynamically_instantiate_spiceyerror(
--> 108             short=short, explain=explain, long=long, traceback=traceback
    109         )
    110 

SpiceSPKINSUFFDATA: 
================================================================================

Toolkit version: CSPICE66

SPICE(SPKINSUFFDATA) --

Insufficient ephemeris data has been loaded to compute the state of -96 (SOLAR PROBE PLUS) relative to 0 (SOLAR SYSTEM BARYCENTER) at the ephemeris epoch 2019 APR 01 00:01:09.185.

spkezr_c --> SPKEZR --> SPKEZ --> SPKGEO

================================================================================

**Comment by rlaker** [comment]
Can you try again? The link Astrospice was using was broken for a bit, but it should work now.

**Comment by MohamedNedal** [comment]
I used 
`kernels = astrospice.registry.get_kernels('psp', 'recon')
`
instead of 
`kernels = astrospice.registry.get_kernels('psp', 'pred')
`
and it works

**Comment by dstansby** [comment]
Looks like this is all fixed now, so I'll close - feel free to re-open or open a new issue if there's still something not working!
